apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireNamespaceNetworkPolicies
metadata:
  name: require-namespace-network-policies
  annotations:
    configsync.gke.io/cluster-name-selector: CLUSTER_2
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
      - kube-system
      - kube-node-lease
      - kube-public
      - gatekeeper-system
      - config-management-system
      - config-management-monitoring
      - resource-group-system
      - istio-system
      - asm-gateways
      - gke-connect
      - default
