apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PolicyStrictOnly
metadata:
  name: policy-strict-constraint
  annotations:
    configsync.gke.io/cluster-name-selector: CLUSTER_1
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups:
          - security.istio.io
        kinds:
          - PeerAuthentication
    namespaces:
      - istio-system
