apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequirenamespaceauthzpolicies
  annotations:
    description: >-
      Requires that every namespace defined in the cluster has an Authorization Policy.
      Note: This constraint is referential. See https://cloud.google.com/anthos-config-management/docs/how-to/creating-constraints#referential
      for details.
spec:
  crd:
    spec:
      names:
        kind: K8sRequireNamespaceAuthzPolicies
      validation:
        openAPIV3Schema: {}
  targets:
    - rego: |
        package k8srequirenamespaceauthzpolicies

        violation[{"msg": msg}] {
          input.review.kind.kind == "Namespace"
          not namespace_has_authzpolicy(input.review.object.metadata.name)
          msg := sprintf("Namespace <%v> does not have an Authorization Policy", [input.review.object.metadata.name])
        }

        namespace_has_authzpolicy(ns) {
          ap := data.inventory.namespace[ns][_].AuthorizationPolicy[_]
        }
      target: admission.k8s.gatekeeper.sh
